name: Deploy to GitHub Pages

on:
  push:
    branches:
      - shoyeb_dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          cd bwc-client
          npm install

      - name: Verify dependencies
        run: |
          cd bwc-client
          npm list

      - name: Build project
        run: |
          cd bwc-client
          npm run build --verbose

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./bwc-client/dist
